/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MagicGUI;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Logger;
import java.util.logging.Level;
/**
 *
 * @author bellaceds
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    
        Connection conn;
        Statement stmt;
        ResultSet rs;
        CallableStatement cs;
        
    public HomePage() {
        initComponents();

        Connection conn;
        Statement stmt;
        ResultSet rs;
        CallableStatement cs;
                
        extraBox1.setVisible(false);
        extraBox2.setVisible(false);
        typeSearch.setVisible(false);
        label1.setVisible(true);
        label2.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardNameText = new javax.swing.JTextField();
        TypeLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        label1 = new javax.swing.JLabel();
        extraBox1 = new javax.swing.JComboBox<>();
        Cost = new javax.swing.JLabel();
        costDropDown = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        typeSearch = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        extraBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardNameText.setText("Name");

        TypeLabel.setText("Card Type");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        label1.setText("Loyalty");

        extraBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        extraBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extraBox1ActionPerformed(evt);
            }
        });

        Cost.setText("Cost");

        costDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        typeSearch.setText("Subtype");

        label2.setText("Loyalty");

        extraBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        extraBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extraBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(extraBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2)
                            .addComponent(costDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cost)
                            .addComponent(extraBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1)
                            .addComponent(TypeLabel)
                            .addComponent(cardNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(typeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(searchButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(cardNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(TypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(extraBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(extraBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(Cost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        Object selectedType = typeComboBox.getSelectedItem();
        selectedType.toString();

        int selectedCost = Integer.valueOf((String)costDropDown.getSelectedItem());

        if (selectedType == "Unspecified")
        {

            try{
                cs = conn.prepareCall("{ call SearchAllByNameAndCost(?,?)}");
                cs.setString("inputName", cardNameText.getText());
                cs.setInt("inputCost", selectedCost);
                cs.executeQuery();

            }catch (SQLException ex){
                Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);

            }

        }
        if (selectedType == "Artifacts")
        {

        }
        if (selectedType == "Creatures")
        {

        }
        if (selectedType == "Enchantments")
        {

        }
        if (selectedType == "Instants")
        {

        }
        if (selectedType == "Lands")
        {

        }
        if (selectedType == "Planeswalker")
        {

        }
        if (selectedType == "Sorceries")
        {

        }

                                          
    }//GEN-LAST:event_searchButtonActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        
        typeComboBox.setSize(366, 35);
        cardNameText.setSize(366, 35);
        costDropDown.setSize(366, 35);
        typeSearch.setSize(366, 35);
        extraBox1.setSize(366, 35);
        extraBox2.setSize(366, 35);

        Object selectedType = typeComboBox.getSelectedItem();
        selectedType.toString();
        //Unspecified, Artifacts, Creatures, Enchantments, Instants, Lands, Planeswalker, Sorceries

        if (selectedType == "Unspecified")
        {
            extraBox1.setVisible(false);
            extraBox2.setVisible(false);
            typeSearch.setVisible(false);

        }
        if (selectedType == "Artifacts")
        {
            extraBox1.setVisible(false);
            extraBox2.setVisible(false);
            typeSearch.setVisible(true);

        }
        if (selectedType == "Creatures")
        {
            label1.setVisible(true);
            label1.setText("Power");
            label2.setVisible(true);

            extraBox1.setVisible(true);
            extraBox2.setVisible(true);
            typeSearch.setVisible(true);

        }
        if (selectedType == "Enchantments")
        {
            extraBox1.setVisible(false);
            extraBox2.setVisible(false);
            typeSearch.setVisible(true);
        }
        if (selectedType == "Instants")
        {
            extraBox1.setVisible(false);
            extraBox2.setVisible(false);
            typeSearch.setVisible(false);
        }
        if (selectedType == "Lands")
        {
            extraBox1.setVisible(false);
            extraBox2.setVisible(false);
            typeSearch.setVisible(true);
        }
        if (selectedType == "Planeswalker")
        {
            label1.setVisible(true);
            label1.setText("Loyalty");

            extraBox1.setVisible(true);
            extraBox2.setVisible(false);
            typeSearch.setVisible(true);
        }
        if (selectedType == "Sorceries")
        {
            extraBox1.setVisible(false);
            extraBox2.setVisible(false);
            typeSearch.setVisible(false);
        }

                                  
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void extraBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extraBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extraBox1ActionPerformed

    private void extraBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extraBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extraBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cost;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JTextField cardNameText;
    private javax.swing.JComboBox<String> costDropDown;
    private javax.swing.JComboBox<String> extraBox1;
    private javax.swing.JComboBox<String> extraBox2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JTextField typeSearch;
    // End of variables declaration//GEN-END:variables
}

